name: Last inn validator-image
description: Hent mcp-linkml-validator image frå GHCR

runs:
  using: composite
  steps:
    - name: Logg inn på GHCR
      shell: bash
      run: echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Hent validator-image frå GHCR
      shell: bash
      run: |
        podman pull ghcr.io/${{ github.repository_owner }}/mcp-linkml-validator:${{ github.sha }}
        podman tag ghcr.io/${{ github.repository_owner }}/mcp-linkml-validator:${{ github.sha }} mcp-linkml-validator:latest
