name: Generer domene
description: Last inn images og generer artefaktar for eit domene

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: linkml-local-image

    - uses: actions/download-artifact@v4
      with:
        name: python-pytest-image

    - name: Last inn images
      shell: bash
      run: |
        podman load < <(gunzip -c linkml-local.tar.gz)
        podman load < <(gunzip -c python-pytest.tar.gz)

    - name: Flattar ut importar (gen-linkml)
      shell: bash
      run: make domain-gen-linkml DOMAIN=${{ inputs.domain }}

    - name: Generer context.jsonld
      shell: bash
      run: make domain-gen-context DOMAIN=${{ inputs.domain }}

    - name: Generer shapes.ttl (SHACL)
      shell: bash
      run: make domain-gen-shapes DOMAIN=${{ inputs.domain }}

    - name: Generer model.py
      shell: bash
      run: make domain-gen-python DOMAIN=${{ inputs.domain }}

    - name: Generer schema.json
      shell: bash
      run: make domain-gen-json-schema DOMAIN=${{ inputs.domain }}

    - name: Generer ontology.ttl (OWL)
      shell: bash
      run: make domain-gen-owl DOMAIN=${{ inputs.domain }}

    - name: Generer schema.ttl (RDF)
      shell: bash
      run: make domain-gen-rdf DOMAIN=${{ inputs.domain }}

    - name: Konverter eksempelfiler til Turtle
      shell: bash
      run: make domain-gen-examples DOMAIN=${{ inputs.domain }}

    - name: Generer dokumentasjon (gen-doc)
      shell: bash
      run: make domain-gen-doc DOMAIN=${{ inputs.domain }}

    - name: Generer ER-diagram
      shell: bash
      run: make domain-gen-erdiagram DOMAIN=${{ inputs.domain }}

    - uses: actions/upload-artifact@v4
      with:
        name: generated-${{ inputs.domain }}
        path: generated/${{ inputs.domain }}/
        retention-days: 1
