FROM python:3.13-alpine

# unngå cache / litt betre runtime
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /work

# installer pytest
COPY requirements-python-test.txt .
RUN pip install --no-cache-dir -r requirements-python-test.txt


# default command (kan overrides)
CMD ["python", "-m", "pytest"]
