name: Generer dokumentasjon (gen-doc)
description: Køyrer gen-doc for alle skjema i domenet eller for eitt skjema

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: false
  schema:
    description: Sti til enkeltskjema
    required: false

runs:
  using: composite
  steps:
    - name: Generer dokumentasjon (gen-doc) — domene
      if: ${{ inputs.domain != '' }}
      shell: bash
      run: make domain-gen-doc DOMAIN=${{ inputs.domain }}
    - name: Generer dokumentasjon (gen-doc) — enkeltskjema
      if: ${{ inputs.schema != '' }}
      shell: bash
      run: make schema-gen-doc SCHEMA=${{ inputs.schema }}
