name: Valider eksempelfiler mot skjema
description: Validerer alle eksempelfiler i domenet mot sine skjema

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: true

runs:
  using: composite
  steps:
    - name: Valider eksempelfiler mot skjema
      shell: bash
      run: make domain-validate-examples DOMAIN=${{ inputs.domain }}
