name: Last inn container-images
description: Hent linkml-local og python-pytest images frå GHCR

runs:
  using: composite
  steps:
    - name: Logg inn på GHCR
      shell: bash
      run: echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Hent images frå GHCR
      shell: bash
      run: |
        podman pull ghcr.io/${{ github.repository_owner }}/linkml-local:${{ github.sha }}
        podman pull ghcr.io/${{ github.repository_owner }}/python-pytest:${{ github.sha }}
        podman tag ghcr.io/${{ github.repository_owner }}/linkml-local:${{ github.sha }} localhost/linkml-local:latest
        podman tag ghcr.io/${{ github.repository_owner }}/python-pytest:${{ github.sha }} localhost/python-pytest:latest
