name: Last inn container-images
description: Last linkml-local og python-pytest images frå workflow-artefaktar

runs:
  using: composite
  steps:
    - name: Last ned linkml-local artefakt
      uses: actions/download-artifact@v4
      with:
        name: linkml-local-image
        path: /tmp/images

    - name: Last ned python-pytest artefakt
      uses: actions/download-artifact@v4
      with:
        name: python-pytest-image
        path: /tmp/images

    - name: Last inn images
      shell: bash
      run: |
        podman load < <(zstd -d -c /tmp/images/linkml-local.tar.zst)
        podman load < <(zstd -d -c /tmp/images/python-pytest.tar.zst)
