name: Generer schema.proto
description: Køyrer gen-proto for alle skjema i domenet

inputs:
  domain:
    description: Domenenamn (ap-no, fair, fint, ngr, oreg, samt)
    required: true

runs:
  using: composite
  steps:
    - name: Generer schema.proto
      shell: bash
      run: make domain-gen-proto DOMAIN=${{ inputs.domain }}
